### ISSUE TITLE
More Parks/ Museums/ Attractions

### ISSUE THREAD

**Issue by Daniela-Procopciuc** [calinpop/TouristApp#3]
Please, can all of you add at least 2 more examples?

- [x] Attractions (Calin)

- [x] Museums (Mihai)

- [x] Parks (Octavian)

**Comment by calinpop** [comment]
I think there is plenty of Attraction`s at this moment

**Comment by mbivol** [comment]
Hi @Daniela-Procopciuc ,
All Museums are done and ready to review.

**Comment by Daniela-Procopciuc** [comment]
well done 👍
